### ISSUE TITLE
Java Native Build not detected 

### ISSUE THREAD

**Issue by uzshrestha** [paketo-buildpacks/java-native-image#107]
## What happened?

I am trying to run entire maven build step (lifecycle) clean-test-package-nativeimage using pack build but seems like it is not possible to do that 
```
pack build spring-petclinic --env BP_JVM_VERSION=8 --env BP_MAVEN_BUILD_ARGUMENTS=spring-boot:build-image
1.1.5-base-cnb: Pulling from paketobuildpacks/run
Digest: sha256:235853acae3609e38e176cc6fb54c04535d44e26e46739aebf0374fe74fd6291
Status: Image is up to date for paketobuildpacks/run:1.1.5-base-cnb
0.11.1: Pulling from buildpacksio/lifecycle
Digest: sha256:2ca9870d9472400792bdc2d43ded8df2642ffcf937e8cd01685836678c28780b
Status: Image is up to date for buildpacksio/lifecycle:0.11.1
===> DETECTING
[detector] 7 of 18 buildpacks participating
[detector] paketo-buildpacks/ca-certificates   2.1.0
[detector] paketo-buildpacks/bellsoft-liberica 7.1.0
[detector] paketo-buildpacks/maven             5.0.0
[detector] paketo-buildpacks/executable-jar    5.0.0
[detector] paketo-buildpacks/apache-tomcat     5.1.0
[detector] paketo-buildpacks/dist-zip          4.0.0
[detector] paketo-buildpacks/spring-boot       4.2.0
```
Native image is only detected if i run `mvn spring-boot:build-image`. If i use this then mvn clean test wont run inside buildpack. 
Thought on this

## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by dmikusa-pivotal** [comment]
So first off...

>pack build spring-petclinic --env BP_JVM_VERSION=8 --env BP_MAVEN_BUILD_ARGUMENTS=spring-boot:build-image

You don't want to do this. It's redundant. Running `pack build` and `mvn spring-boot:build-image` are functionally the same thing. You're telling pack to start containers to build using Maven, which in turn makes more containers to build your native image.

If you have maven installed locally or have the `mvnw` wrapper, you can use that directly. If you prefer to use `pack build` that's OK too. You just want to run `pack build spring-petclinic --env BP_NATIVE_IMAGE=true`, like seen here https://paketo.io/docs/buildpacks/language-family-buildpacks/java-native-image/#building-from-source. 

Setting that env variable is crucial as that is what causes native-image to run. See https://github.com/paketo-buildpacks/native-image#configuration

Hope that helps!

**Comment by uzshrestha** [comment]
Thank you for quick response
