### ISSUE TITLE
Support spring boot 3.0 native build with bellsoft-liberica:9.9.0-ea

### ISSUE THREAD

**Issue by showpune** [paketo-buildpacks/java-native-image#502]
## Describe the Enhancement
I am working on a demo using spring 3.0 for native image with BP, I found the bug https://github.com/spring-projects/spring-boot/issues/32878, it is mentioned that bellsoft-liberica:9.9.0-ea, which version of [java-native-image](https://github.com/paketo-buildpacks/java-native-image) will support spring 3.0 build?

**Comment by pivotal-david-osullivan** [comment]
Closing this issue as the GA release with Boot 3/Native support was released following the Early Access test version
